# MEMO 一人での開発でlintは無理してやらなくて良いと判断してコメントアウト

# name: Lint

# on:
#   push:
#     branches:

# permissions:
#   checks: write
#   contents: write

# jobs:
#   lint:
#     name: ESLint
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v4

#       - name: Install packages
#         run: npm install

#       - name: Run lint
#         run: npm run lint
